---

- name: Dump database structure on source.
  shell: >
    mysqldump {{ item.database }}
    --no-data
    > {{ mysql_sync_source_dump_dir }}/{{ item.database }}.sql
  delegate_to: "{{ item.source }}"
  remote_user: "{{ mysql_sync_remote_user }}"
  with_items: mysql_sync_config
  always_run: yes
  when: mysql_sync_create_dump|default(true)

- name: Dump database on source.
  shell: >
    mysqldump {{ item.database }}
    {{ item.skip_tables|default('')|join(' --ignore-table ' ~ item.database ~ '.')|regex_replace('^(.)', ' --ignore-table ' ~ item.database ~ '.' ~ '\\1')}}
    >> {{ mysql_sync_source_dump_dir }}/{{ item.database }}.sql
  delegate_to: "{{ item.source }}"
  remote_user: "{{ mysql_sync_remote_user }}"
  with_items: mysql_sync_config
  always_run: yes
  when: mysql_sync_create_dump|default(true)